---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pedrosel/public_html/sygna
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && npm run build
